version: '2.3'
services:
  lab2aos:
    image: lab2aos-hw
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=dockerUser
      - DATABASE_PASSWORD=dockerPassword
      - DATABASE_NAME=lab2db
      - DATABASE_PORT=3306
  db:
    image: mysql:latest
    volumes:
      - type: bind
        source: ./src/main/resources/dbscripts
        target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=MySQL4298-=
      - MYSQL_DATABASE=lab2db
      - MYSQL_USER=dockerUser
      - MYSQL_PASSWORD=dockerPassword
    ports:
      - 3306:3306